# Generated by Django 2.2.9 on 2020-04-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0004_auto_20200414_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(),
        ),
    ]
